### ISSUE TITLE
微机原理突击纲

### ISSUE THREAD

**Issue by Koi-Blue** [Koi-Blue/Koi-Blue.github.io#16]
![微机导图.png](https://www.helloimg.com/i/2024/12/10/6757ee916722d.png)

### 4页 从源程序到能够被计算机执行的程序（以C语言程序为例）

1. **预处理**：在编译器开始实际编译之前，预处理器会根据源代码中的指令（如`#include`、`#define`等）进行文本替换和文件包含操作。最终生成一个融合了头文件内容的纯C语言程序文本文件（`.i`）。
2. **编译**：编译器将预处理后的`.i`文件转换为汇编语言程序（`.s`）。这个过程包括语法分析、语义分析、优化等多个步骤，确保程序逻辑正确并尽可能高效。
3. **汇编**：汇编器将汇编语言程序（`.s`）转换为机器码形式的目标文件（`.o`），这些目标文件是二进制格式，但还不是可以直接运行的程序，因为它们可能依赖于其他库函数或模块。
4. **连接**：链接器负责将多个目标文件（`.o`）以及所需的库文件集成在一起，解决符号引用问题，生成最终的可执行文件（`.exe`）。这一步骤中，链接器还会处理不同模块之间的地址调整，确保所有部分都能正确协同工作。

### 18页 什么是嵌入式系统

嵌入式系统是一种专用于控制、监视或辅助操作机器和设备的专用计算机系统。它通常由以下三部分构成：
- **嵌入式处理器**：核心计算单元，可以是微控制器（MCU）、数字信号处理器（DSP）或其他类型的处理器。
- **相关硬件设备**：包括传感器、执行器、通信接口等，用于与外部世界交互。
- **嵌入式软件**：运行在嵌入式处理器上的应用程序，实现特定的功能需求。这类软件通常是实时操作系统（RTOS）或者裸机程序（Bare Metal Programming）。

### 20页 并发与并行

- **并发**：指的是在一个时间段内，系统能够处理多个任务的能力。尽管在任何一个给定的时间点上只有一个任务在执行，但由于任务切换速度非常快，从宏观上看就像是多个任务同时进行。在单核CPU上，通过时间片轮转机制来实现多任务的并发执行。
- **并行**：是指在同一时间点上有多个任务真正地同时执行。要实现真正的并行，必须有多核或多处理器的支持，每个核心或处理器可以独立执行不同的任务。
- **进程**：是一个独立的执行环境，包含了程序执行所需的所有资源，如内存空间、文件描述符等。一个进程中可以有多个线程作为执行单元，线程共享进程的资源，但在调度时被视为独立的单位。

### 21页 流水线技术（并行流水线技术）

流水线技术是现代处理器提高指令吞吐量的关键手段之一。通过将指令的执行过程划分为多个阶段（如取指、解码、执行、访存、写回），并将这些阶段分布在不同的硬件单元中，使得多个指令可以在不同阶段同时进行，从而提高了整体的执行效率。并行流水线技术进一步扩展了这一概念，允许同一时间内多个指令的不同阶段在不同流水线上并行执行。

### 27页 进制编码

BCD（Binary-Coded Decimal）是一种用二进制表示十进制数的方法。最常用的BCD码是8421码，其中每一位二进制位代表十进制数的一个权重（8, 4, 2, 1）。例如，`(0010 0011 0100.0001 0101)BCD` 对应的十进制数是 `234.15`。需要注意的是，BCD码只适用于表示0到9的十进制数字，超出这个范围的二进制值对于BCD是非法的。

### 33页 补码的运算（进制转换）

补码是一种用于表示有符号整数的编码方式，广泛应用于计算机系统中。补码的优势在于它可以简化加法和减法运算，避免了对负数的特殊处理。对于n位的二进制数，其补码可以通过对其原码按位取反再加1得到。例如，8位二进制数`0000 0010`（即十进制2）的补码仍然是`0000 0010`，而`1111 1110`（即十进制-2）的补码则是`1111 1110`。

### 37页 运算中的溢出问题，无符号数和有符号数

- **无符号数**：只能表示非负整数，范围是从0到 $2^n - 1$ ，其中n是位数。
- **有符号数**：可以表示正数和负数，范围取决于使用的编码方式（如补码）。对于n位的补码表示，范围是从 $-2^{n-1}$ 到 $2^{n-1} - 1$ 。
- **溢出**：当运算结果超出了数据类型所能表示的范围时，就会发生溢出。对于无符号数，溢出会导致结果“环绕”；而对于有符号数，溢出可能会导致错误的结果，因此需要特别注意检测和处理。

![微机1.png](https://s2.loli.net/2024/12/06/5GdPtva4F1cixuq.png)
![微机2.png](https://s2.loli.net/2024/12/06/sOdeSftgGhNuVn3.png)

### 41页 基本逻辑门

基本逻辑门是构建数字电路的基础元件，常见的逻辑门包括：
- **与门（AND Gate）**：只有当所有输入都为高电平时，输出才为高电平。
- **或门（OR Gate）**：只要有一个输入为高电平，输出就为高电平。
- **与非门（NAND Gate）**：与门的反相输出，即只要有一个输入为低电平，输出就为高电平。
- **或非门（NOR Gate）**：或门的反相输出，即只有当所有输入都为低电平时，输出才为高电平。
- **异或门（XOR Gate）**：当两个输入不同时，输出为高电平；当两个输入相同时，输出为低电平。
- **同或门（XNOR Gate）**：异或门的反相输出，即当两个输入相同时，输出为高电平；当两个输入不同时，输出为低电平。

### 44页 三八译码器

三八译码器（3-to-8 Line Decoder）是一种常用的数字电路，用于将3位二进制输入转换为8个单独的输出线。它的主要功能是根据输入的3位二进制码选择一个对应的输出线激活（高电平），其余输出线保持低电平。三八译码器通常具有使能端（Enable），只有当使能端为有效状态时，译码器才会工作。常见的应用包括地址译码、控制信号分配等。

### 53页 多核技术

多核技术是指在一个处理器芯片内部集成多个独立的核心（Core），每个核心都可以独立执行程序。多核处理器的优点包括：
- 提高并行处理能力，支持更多的任务同时运行。
- 降低功耗，相比单核处理器，在相同性能下可以更节能。
- 改善响应速度，特别是在多任务环境下，可以更好地满足实时性要求。

### 57页 8086/8088

![1733742517783.png](https://www.helloimg.com/i/2024/12/09/6756ce28c137a.png)

#### 2.2 x86处理器特点

- **流水线**：8086/8088处理器采用了简单的流水线结构，主要包括取指、解码、执行三个阶段。流水线技术提高了指令的吞吐量，但也会引入一些复杂性，如分支预测和异常处理。
- **内存分段**：8086/8088使用了分段内存模型，将内存分为多个逻辑段，如代码段（CS）、数据段（DS）、堆栈段（SS）等。每个段都有自己的基地址和长度，通过段寄存器来管理和访问。
- **支持多处理器**：虽然8086/8088本身是单核处理器，但它可以通过外设（如APIC）支持多处理器系统，允许多个处理器协同工作。

![1733742635015.png](https://www.helloimg.com/i/2024/12/09/6756ce9e29957.png)

### 62页 8086/8088内部寄存器

8086/8088处理器共有14个16位寄存器，分为以下几类：
- **通用寄存器**：AX、BX、CX、DX，用于存储数据和地址。
- **指针寄存器**：SP（堆栈指针）、BP（基址指针），用于管理堆栈和数据访问。
- **索引寄存器**：SI（源索引）、DI（目的索引），用于数组和字符串操作。
- **段寄存器**：CS（代码段）、DS（数据段）、SS（堆栈段）、ES（附加段），用于分段内存管理。
- **指令指针**：IP（指令指针），指向当前正在执行的指令。
- **标志寄存器**：FLAGS，包含多个标志位，用于表示运算结果的状态（如零标志、进位标志等）。

### 64页 控制寄存器

在x86架构中，**Flags标志寄存器**（通常简称为`FLAGS`）是一个16位的寄存器，用于保存CPU的各种状态和控制信息。它分为两类标志位：**状态标志位**和**控制标志位**。以下是详细的说明：

#### 状态标志位

状态标志位反映了最近一次算术或逻辑操作的结果，用于条件转移指令和其他需要根据操作结果做出决策的地方。

- **CF (Carry Flag, 进位/借位标志)**：
  - 当无符号数运算产生进位或借位时设置为1，否则为0。
  - 例如，在加法操作中，如果最高有效位产生了进位，则CF=1；在减法操作中，如果发生了借位，则CF=1。

- **PF (Parity Flag, 奇偶标志)**：
  - 表示结果的最低8位中1的数量是偶数还是奇数。
  - 如果1的数量是偶数，则PF=1；如果是奇数，则PF=0。
  - 主要用于某些特定类型的校验。

- **AF (Auxiliary Flag, 辅助进位标志)**：
  - 在BCD调整指令中使用，表示低4位是否有进位或借位。
  - 如果在第3位到第4位之间有进位或借位，则AF=1；否则为0。

- **ZF (Zero Flag, 零标志)**：
  - 如果操作结果为0，则ZF=1；否则为0。
  - 常用于判断两个数是否相等或是否为零。

- **SF (Sign Flag, 符号标志)**：
  - 反映结果的最高有效位（即符号位），用于表示有符号数的正负。
  - 如果最高有效位为1（表示负数），则SF=1；如果为0（表示正数），则SF=0。

- **OF (Overflow Flag, 溢出标志)**：
  - 当有符号数运算结果超出可表示范围时设置为1，否则为0。
  - 例如，在带符号整数加法中，如果结果超出了可以表示的最大或最小值，则OF=1。

#### 控制标志位

控制标志位影响CPU的操作模式和行为，主要用于调试、中断处理和字符串操作。

- **TF (Trap Flag, 捕捉标志)**：
  - 当设置为1时，启用单步调试模式。每执行一条指令后，CPU会触发一个单步中断（INT 1），允许程序员逐条检查程序执行情况。
  - 通常用于开发和调试过程中。

- **IF (Interrupt Flag, 中断允许标志)**：
  - 控制外部可屏蔽中断的允许或禁止。
  - IF=1时，允许外部中断；IF=0时，禁止外部中断。
  - 可以通过CLI（清除中断标志）和STI（设置中断标志）指令来改变IF的状态。

- **DF (Direction Flag, 方向标志)**：
  - 决定字符串操作指令（如`MOVS`、`SCAS`等）的处理方向。
  - DF=0时，字符串操作从低地址向高地址进行（增量模式）；DF=1时，字符串操作从高地址向低地址进行（减量模式）。
  - 可以通过CLD（清除方向标志）和STD（设置方向标志）指令来改变DF的状态。

### 67页 段寄存器的组合规则

![1733742707571.png](https://www.helloimg.com/i/2024/12/09/6756cee62f860.png)

段寄存器用于分段内存管理，每个段寄存器对应一个逻辑段。段寄存器的组合规则如下：
- **代码段（CS）**：用于存放指令代码，通过CS:IP访问。
- **数据段（DS）**：用于存放数据，通过DS:BX、DS:SI等访问。
- **堆栈段（SS）**：用于管理堆栈，通过SS:SP访问。
- **附加段（ES）**：用于额外的数据访问，通常用于字符串操作，通过ES:DI访问。

### 70页 时钟周期，总线周期概念

- **时钟周期**：是处理器的基本时间单位，由时钟信号决定。每个时钟周期内，处理器可以完成一个基本的操作，如取指、解码等。
- **总线周期**：是指处理器与外部设备（如内存、I/O端口）进行一次数据传输所需的时间。一个总线周期通常由多个时钟周期组成，具体取决于总线的速度和负载情况。

### 71页 图2-12 引脚作用

![1733742292882.png](https://www.helloimg.com/i/2024/12/09/6756cd4d80093.png)

![1733742343655.png](https://www.helloimg.com/i/2024/12/09/6756cd79a7a71.png)

在8086/8088处理器中，引脚的作用非常重要，尤其是在与外部设备通信时。图2-12展示了8086/8088的主要引脚及其作用，其中包括：
- **地址总线（A0-A19）**：用于发送地址信号，指定要访问的内存或I/O端口地址。
- **数据总线（D0-D15）**：用于传输数据，8088为8位数据总线，8086为16位数据总线。
- **控制总线**：包括读/写信号（RD、WR）、中断请求（INT）、复位信号（RESET）等，用于控制处理器的行为。
- **等待周期（TW）**：当外部设备无法及时响应时，处理器会插入等待周期，以确保数据传输的正确性。

### 114页 寻址方式

寻址方式决定了如何获取指令的操作数。常见的寻址方式包括：
- **立即数寻址**：操作数直接出现在指令中，不需要访问内存。

  ``` asm
  MOV AX, 1234H     ; 把立即数 1234H 装入 AX
  ```

- **寄存器寻址**：操作数存放在寄存器中，指令直接指定寄存器编号。
  
  ``` asm
  MOV BX, AX     ; 把 AX 的值传递（复制）给 BX
  ```

- **直接寻址**：操作数存放在内存中，指令中给出内存地址。
  
  ``` asm
  MOV AX, [1234H]     ; 从内存地址 1234H 取数据装入 AX
  ```
  
- **间接寻址**：操作数存放在内存中，指令中给出一个地址指针，通过该指针访问内存中的操作数。
  
  ``` asm
  MOV AX, [BX]    ; BX 中存储的是地址，通过 BX 取出该地址上的数据
  ```
  
- **基址寻址**：操作数存放在内存中，指令中给出一个偏移量，通过基址寄存器加上偏移量计算出实际地址。
  
  ``` asm
  MOV AX, [BX + 04H]    ; 基址 BX 加偏移量 04H，找到操作数
  ```
  
- **变址寻址**：操作数存放在内存中，指令中给出一个偏移量，通过变址寄存器加上偏移量计算出实际地址。
  
  ``` asm
  MOV AX, [SI + 08H]    ; 变址 SI 加偏移量 08H，找到操作数
  ```
  
- **相对寻址**：操作数存放在内存中，指令中给出一个相对偏移量，通过当前指令指针加上偏移量计算出实际地址。

（不需要计算物理地址：立即数寻址和寄存器寻址）

寻址方式判断和求寄存器内容可以读[这篇文章](https://blog.csdn.net/weixin_44015158/article/details/111937895)。

### 124页 指令对操作数的要求

（判断指令正确与否）
堆栈操作的指令 push pop

在x86指令集中，指令对操作数的要求非常严格，必须遵循一定的规则。例如：
- **单操作数指令**：如`PUSH`、`POP`等，操作数可以是寄存器或内存地址。
  
  ``` asm
  PUSH AX    ; 将 AX 的内容压入堆栈
  POP BX     ; 从堆栈弹出数据到 BX
  ```
  > **注意**：PUSH 和 POP 的操作数只能是寄存器或内存，不能是立即数。

- **双操作数指令**：如`MOV`、`ADD`等，通常第一个操作数为目标操作数，第二个操作数为源操作数。目标操作数可以是寄存器或内存地址，源操作数可以是寄存器、内存地址或立即数。
- **指针运算符**：如`PTR`，用于明确指定操作数的大小（字节、字、双字等），确保指令正确解析。

### 125页 为什么要用堆栈

（一个保护断点（地址压入堆栈），一个保护现场），堆栈的原则（*）

堆栈是一种后进先出（LIFO）的数据结构，广泛应用于程序执行过程中。堆栈的主要用途包括：
- **保护断点**：当调用子程序时，返回地址会被压入堆栈，以便子程序执行完毕后能够正确返回到调用点。
- **保护现场**：在中断处理或函数调用时，保存当前的寄存器状态，确保恢复后程序能够继续正常执行。
- **参数传递**：在函数调用时，参数可以压入堆栈，供被调用函数使用。
- **局部变量存储**：函数内部的局部变量通常也存储在堆栈中，便于动态分配和释放。

### 128页 第一段第一二行：设置堆栈的原因

> [!NOTE]
> 堆栈除了在子程序调用和相应中断时用于保护断点地址外，还可以需要时对某些寄存器内容进行保存

> 设置堆栈的原因主要是为了提供一种灵活且高效的机制来管理函数调用、中断处理和局部变量。通过堆栈，程序可以方便地保存和恢复上下文信息，确保程序的正确性和稳定性。常见的设置堆栈指令包括`PUSH`、`POP`、`LEA`等。

### 130页 输入输出指令

输入输出指令用于与外部设备进行通信。常见的输入输出指令包括：
- **IN**：从指定的I/O端口读取数据，存入寄存器（如AL、AX）。
  
  ``` asm
  IN AL, 60H    ;从端口 60H 读取数据到 AL
  ```
  
- **OUT**：将寄存器（如AL、AX）中的数据写入指定的I/O端口。
  
  ``` asm
  OUT 60H, AL    ;将 AL 中的数据写到端口 60H
  ```
  

- **DX寄存器**：当I/O端口地址超过8位时，使用DX寄存器存放高8位地址，AL或AX存放低8位或16位地址。
  
  ``` asm
  MOV DX, 60H
  IN AL, DX    ;通过 DX 指定端口读取数据到 AL
  ```
  

### 134页 减法指令

减法指令用于执行减法运算，常见的减法指令包括：
- **SUB**：从目标操作数中减去源操作数，结果存入目标操作数。
- **SBB**：带借位的减法，从目标操作数中减去源操作数和进位标志（CF），结果存入目标操作数。SBB常用于多字节减法运算。

### 136页 比较指令 cmp

比较指令`CMP`用于比较两个操作数的大小，但不会保存结果，而是通过修改标志寄存器（FLAGS）中的标志位来反映比较结果。`CMP`实际上相当于执行了一次减法操作，但不改变操作数的值。例如：
- `CMP AX, BX`：比较AX和BX的值，更新标志寄存器中的零标志（ZF）、符号标志（SF）、进位标志（CF）等。

### 140页 逻辑与指令

逻辑与指令`AND`用于执行按位与运算，常用于屏蔽某些位或清除特定位。`AND`指令的操作数可以是寄存器、内存地址或立即数。例如：
- `AND AL, 0F0H`：将AL寄存器的低4位清零，保留高4位。

### 142页 测试指令 test

测试指令`TEST`类似于`AND`指令，但它不会保存结果，而是通过修改标志寄存器中的标志位来反映测试结果。`TEST`常用于检查某些位是否为1或0。例如：
- `TEST AL, 01H`：检查AL寄存器的最低位是否为1，更新零标志（ZF）。

### 143页 逻辑左移和算术左移

- **逻辑左移（SHL）**：将操作数的每一位向左移动指定的位数，空出的低位用0填充。逻辑左移常用于乘法运算（如乘以2的幂）。
- **算术左移（SAL）**：与逻辑左移相同，但在处理有符号数时，算术左移会保留符号位，确保结果的符号正确。SAL和SHL在x86指令集中实际上是相同的指令，但对于有符号数的处理，推荐使用SAL。

### 184页 取值运算符

取值运算符用于获取变量的值或地址。常见的取值运算符包括：

![1733626089683.png](https://www.helloimg.com/i/2024/12/08/6755076d85f25.png)

### 185页 伪指令（操作码）

4.2 伪指令不是真正的机器指令，而是汇编器用来指导汇编过程的指令。

![1733626981851.png](https://www.helloimg.com/i/2024/12/08/67550ae2cc374.png)

![微机3.png](https://www.helloimg.com/i/2024/12/08/6755083a2addd.png)

常见的伪指令包括：
- **SECTION**：定义代码段或数据段。
- **EXTERN**：声明外部符号，表示该符号将在其他文件中定义。
- **GLOBAL**：声明全局符号，表示该符号可以在其他文件中引用。
- **DB/DW/DD**：定义字节、字、双字的数据。
- **EQU**：定义常量，如`SIZE EQU 10`。

### 186页 例4-3
变量在内存中的存放顺序
![1733627081470.png](https://www.helloimg.com/i/2024/12/08/67550b468b756.png)

### 197页 DOS系统功能调用方法

DOS系统功能调用是通过中断（INT 21H）来实现的。调用时，程序需要设置AH寄存器为功能号，并根据具体功能设置其他寄存器或内存中的参数。例如：
- `INT 21H, AH=09H`：显示字符串，字符串地址存放在DX寄存器中。

### 203页 2 的4567

![1733627209279.png](https://www.helloimg.com/i/2024/12/08/67550bc8c1893.png)

> [!TIP]
> 这部分内容需要详细回答。

### 226页 6264芯片

6264是一款静态随机存取存储器（SRAM），具有8K×8的存储容量。它的地址线为A0-A12（共13根），可以寻址8192个地址；数据线为D0-D7（共8根），每次可以读写8位数据。SRAM的特点是速度快、无需刷新，但功耗较高，适合用于缓存或高速缓冲区。

### 230页 DRAM刷新

动态随机存取存储器（DRAM）由于其存储单元的电容特性，需要定期刷新以保持数据的完整性。刷新操作通常由内存控制器自动完成，每隔一定时间（如64ms）对所有行进行一次刷新。刷新操作会影响系统的性能，因此现代DRAM采用了多种优化技术，如自刷新模式、分布式刷新等。

### 231页 地址译码的方式

地址译码是将CPU发出的地址信号转换为具体的物理地址，以便正确访问内存或I/O端口。常见的地址译码方式包括：
- **全地址译码**：所有地址线都参与译码，确保每个地址唯一对应一个存储单元或I/O端口。
- **部分地址译码**：只有部分地址线参与译码，可能导致地址重叠，适用于简单的系统或小规模存储器。

### 233页 仅用一位的线选译码

线选译码是一种简单的地址译码方式，通常用于选择一组存储器芯片或I/O端口。例如，使用一个使能信号（如CS）来选择一组8K×8的SRAM芯片，而不对每个芯片进行单独的地址译码。这种方式简单易实现，但灵活性较差。

### 234页 例5-1

![1733746259152.png](https://www.helloimg.com/i/2024/12/09/6756dcc80d227.png)

**各种ROM的名字和特性**
常见的只读存储器（ROM）类型包括：
- **EPROM（可擦除可编程只读存储器）**：可以通过紫外线擦除数据，重新编程。
- **EEPROM(E<sup>2</sup>PROM)（电可擦除可编程只读存储器）**：可以通过电信号擦除和编程，支持字节级别的擦写操作。
- **Flash ROM**：一种特殊的EEPROM，支持大块数据的快速擦除和编程，广泛应用于固件存储。
- **PROM（可编程只读存储器）**：只能编程一次，一旦写入数据后无法更改。

### 239页 EEPROM擦除

EEPROM的擦除操作是通过施加特定的电压或电流来实现的。擦除过程通常比编程过程慢得多，且有一定的寿命限制（如10万次擦写周期）。擦除操作可以针对整个芯片或单个字节进行，具体取决于EEPROM的类型和设计。

![1733828758439.png](https://www.helloimg.com/i/2024/12/10/67582094a02ac.png)

### 244页 存储器扩展技术

存储器扩展技术用于增加系统的存储容量，常见的扩展方式包括：
- **字扩展**：通过增加数据线的数量来扩展存储器的位宽。例如，将两片8位SRAM芯片并联，形成16位的存储器。
- **位扩展**：通过增加地址线的数量来扩展存储器的地址空间。例如，将两片8K×8的SRAM芯片串联，形成16K×8的存储器。
- **字位扩展**：同时进行字扩展和位扩展，以达到更大的存储容量。

### 246页 例5-4

![1733627635231.png](https://www.helloimg.com/i/2024/12/08/67550d82a5242.png)

![1733627652573.png](https://www.helloimg.com/i/2024/12/08/67550d82dacfe.png)

### 247页 例5-5

![1733746351503.png](https://www.helloimg.com/i/2024/12/09/6756dd22ba579.png)

### 249页 例5-7

![1733627733362.png](https://www.helloimg.com/i/2024/12/08/67550dd1aaa00.png)

![1733627783149.png](https://www.helloimg.com/i/2024/12/08/67550e03d239a.png)

> 计算存储器的容量。公式为：`容量 = (末地址 - 首地址 + 1)`。理解存储器地址空间的计算方法。

### 259页 作业第七题

![1733627837175.png](https://www.helloimg.com/i/2024/12/08/67550e395af45.png)

- 地址范围为 `00000H ~ 7FFFFH`，即需要构成 **512 KB** 的内存。
- 每片 DRAM 芯片的容量为 $64K \times 1$ bit。

---

#### 1. 目标总存储容量
- 地址范围 `00000H ~ 7FFFFH` 表示内存总容量为：

$$
  7FFFF_H - 00000_H + 1 = 512 \text{KB}
$$

#### 2. 单片 DRAM 芯片的存储能力
- 单片 DRAM 芯片的容量为 $64K \times 1$ bit。
- 一个字节（Byte）由 8 位（bit）组成，因此：

$$
  1 \text{片 DRAM 的字节存储容量} = \frac{64K \text{bits}}{8} = 8 \text{KB}
$$

#### 3. 组装一组字节存储
- 为了存储 1 字节的数据，需要 8 片 DRAM 芯片（每片提供 1 位存储能力）。
- 一组 8 片 DRAM 芯片可以存储：

$$
  8 \text{KB} \times 8 \text{片} = 64 \text{KB}
$$

#### 4. 计算总需求的组数
- 总目标存储容量为 512 KB，每组 DRAM 芯片存储 64 KB，因此需要的组数为：

$$
  \frac{512 \text{KB}}{64 \text{KB}} = 8 \text{组}
$$

#### 5. 计算总芯片数
- 每组需要 8 片 DRAM 芯片，总共需要的芯片数为：

$$
  8 \text{组} \times 8 \text{片/组} = 64 \text{片}
$$

---

### 265页 IO端口编址

![1733899107672.png](https://www.helloimg.com/i/2024/12/11/6759335ea73d7.png)

IO端口编址是指为I/O设备分配唯一的地址，以便CPU能够正确访问这些设备。常见的IO端口编址方式包括：
- **独立编址**：I/O端口与内存地址分开编址，使用专门的指令（如IN、OUT）进行访问。8086/8088处理器支持64K个I/O端口地址（0000H-FFFFH）。
- **统一编址**：I/O端口与内存地址统一编址，使用相同的指令（如MOV）进行访问。这种方式简化了编程，但减少了可用的内存地址空间。

### 6.2 输入接口和输出接口

输入接口和输出接口是连接CPU与外部设备的桥梁，它们负责数据的传输和控制。输入接口的主要功能是接收来自外部设备的数据，输出接口的主要功能是将数据发送到外部设备。常见的输入接口和输出接口包括：
- **锁存器**：用于暂时保存数据，确保数据的稳定传输。
- **控制寄存器**：用于配置接口的工作模式和状态。

#### 1. 无条件传送
- **概念**：直接将数据从 CPU 传送到 I/O 设备，或从 I/O 设备传送到 CPU，没有任何条件判断。
- **特点**：
  - **简单直接**：无需判断设备状态。
  - **低效**：设备可能未准备好接收/发送数据，但 CPU 仍强制进行操作。
- **应用场景**：通常用于简单设备（如灯光控制）或对速度要求较低的情况。

---

#### 2. 查询
- **概念**：CPU 通过轮询方式反复检查 I/O 设备的状态，当设备准备好后，再传输数据。
- **特点**：
  - **CPU 主动**：CPU 需要不断查询设备状态，直到设备准备就绪。
  - **效率低**：在等待期间 CPU 会被占用。
- **典型实现**：使用状态寄存器：
  - CPU 读取设备状态位。
  - 检测设备是否准备好传输数据。
- **应用场景**：适合低速设备或场景较少的外设。

---

#### 3. 中断控制
- **概念**：由 I/O 设备主动向 CPU 发出中断请求，通知 CPU 准备传输数据。
- **特点**：
  - **设备主动**：I/O 设备控制数据传输的时机，CPU 只在需要时响应。
  - **效率高**：CPU 不需要轮询设备，能够专注于其他任务。
  - **中断响应流程**：CPU 暂停当前任务，跳转到中断服务程序（ISR）处理 I/O 操作。
- **应用场景**：高效数据传输，适合速度较高的设备或实时性要求较高的场景。

---

#### 4. 直接存储器访问（DMA）
- **概念**：通过 DMA 控制器，直接将 I/O 设备的数据传输到内存，或将内存数据传输到设备，而不需要 CPU 的参与。
- **特点**：
  - **CPU 减负**：DMA 控制器负责数据传输，CPU 只需设置 DMA 参数。
  - **速度快**：适合大批量数据传输。
- **应用场景**：用于高速设备（如硬盘、显卡）与内存之间的大量数据交换。

---

#### 对比重点

| **方式**         | **数据传输控制** | **效率**  | **应用场景**              |
|-------------------|------------------|-----------|---------------------------|
| 无条件传送        | 无判断           | 最低      | 简单设备，控制需求较低    |
| 查询              | CPU 主动         | 低        | 低速设备，状态简单        |
| 中断控制          | 设备主动         | 高        | 高速设备，实时性较高      |
| 直接存储器访问    | DMA 控制器       | 最高      | 高速设备，大量数据传输    |

---

#### 总结重点
- **效率层级**：无条件传送 < 查询 < 中断控制 < DMA。
- **灵活性**：中断和 DMA 更灵活，但硬件要求更高。
- **适用场景**：根据设备速度和数据量选择适当的方式。

### 276页 DMA控制功能

![1733899335826.png](https://www.helloimg.com/i/2024/12/11/6759344227461.png)

DMA（Direct Memory Access）是一种高效的数据传输方式，允许I/O设备直接与内存进行数据交换，而无需CPU的介入。DMA控制器负责管理数据传输的过程，确保数据的正确性和完整性。DMA特别适用于需要高速数据传输的场景，如磁盘读写、网络通信等。

### 279页 中断源

中断源是指触发中断请求的来源，分为内部中断和外部中断：
- **内部中断**：由CPU内部事件触发，如除法错误、非法指令等。
- **外部中断**：由外部设备触发，如键盘按下、定时器超时等。

中断服务过程包括以下几个步骤：
1. **中断请求**：外部设备或内部事件触发中断请求。
2. **中断响应**：CPU暂停当前任务，保存上下文信息（如寄存器状态）。
3. **中断服务**：CPU跳转到中断服务程序（ISR），执行相应的处理逻辑。
4. **中断返回**：中断服务程序执行完毕后，CPU恢复上下文信息，继续执行原任务。

### 284页 图6-23下

![1733899425011.png](https://www.helloimg.com/i/2024/12/11/6759349b0650a.png)

中断向量是中断服务程序的入口地址，通常由四个字节组成，前两个字节表示偏移地址（IP），后两个字节表示段地址（CS）。在实模式下，每个中断向量占用4个字节，总共可以容纳256个中断向量（0-255）。

### 289页 8259

8259A 是一款可编程中断控制器，用于管理多个中断源。通过级联多个8259芯片，可以扩展系统的中断处理能力。例如，9片8259芯片可以管理最多64个中断源。8259的主要功能包括：
- **优先级管理**：根据中断源的优先级，决定哪个中断先被处理。
- **中断屏蔽**：通过设置屏蔽寄存器，可以选择性地禁止某些中断源。
- **中断结束**：在中断服务程序执行完毕后，通知8259中断已处理完毕。

### 294页 级联工作方式

级联工作方式是指通过多个8259芯片的级联，扩展系统的中断处理能力。例如，4片8259芯片可以管理29个中断源（4×8−3）。级联工作方式的实现涉及到主从关系的配置、中断优先级的设定以及中断传递的机制。

### 8253/8255

8253是一款可编程定时器/计数器，广泛应用于定时、延时、频率测量等场景。8255是一款可编程并行接口芯片，用于实现CPU与外部设备之间的并行数据传输。两者都是嵌入式系统中常用的重要组件。

### 326页 8253方式3

8253的工作方式3是一种方波发生器模式，用于生成连续的方波信号。在这种模式下，8253会在计数值到达0时自动重新加载初始值，并继续计数。方波的频率取决于计数值和时钟频率。方式3常用于产生定时脉冲或同步信号。

![1733798858107.png](https://www.helloimg.com/i/2024/12/10/6757aa379e13c.png)

### 例7-1

![1733817250805.png](https://www.helloimg.com/i/2024/12/10/6757f3a2aa7eb.png)

![1733798724089.png](https://www.helloimg.com/i/2024/12/10/6757a9b48ed5c.png)

![1733798742674.png](https://www.helloimg.com/i/2024/12/10/6757a9c3b488d.png)

### 338页 8255工作方式

8255有三种工作方式，分别适用于不同的应用场景：
- **方式0（基本输入/输出）**：提供简单的并行输入和输出功能，适用于不需要握手信号的基本I/O操作。
- **方式1（选通输入/输出）**：增加了握手信号的支持，允许更复杂的I/O操作，如确认接收或发送完成。
- **方式2（双向数据传送）**：支持双向数据传送，并且具有自动握手能力，适合用于需要高速数据交换的应用场景。

每个端口（A、B、C）都可以独立配置为上述任何一种工作模式，或者组合使用，以满足不同外设的要求。

**Comment by DELIGT-code** [comment]
别学了牢大

**Comment by Koi-Blue** [comment]
> 别学了牢大

要坠了
